# Use a Go official image as a base image
FROM golang:1.19 as builder

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go app
RUN go build -o main ./cmd/grpc_server

# Start a new stage from scratch
FROM debian:bullseye-slim

# Copy the pre-built binary from the previous stage
COPY --from=builder /app/main /app/main

# Expose port 50051 to the outside world
EXPOSE 50051

# Command to run the executable
CMD ["/app/main"]
