# config.yaml

grpc:
  server:
    host: "0.0.0.0"
    port: 50051
    # TLS settings (if needed)
    tls:
      enabled: false
      cert_file: "config/cert.pem"
      key_file: "config/key.pem"

pulsar:
  serviceURL: "pulsar://localhost:6650"
  functions:
    orderProcessing:
      inputTopic: "orders-topic"
      outputTopic: "processed-orders-topic"
    paymentProcessing:
      inputTopic: "processed-orders-topic"
      outputTopic: "payment-results-topic"
    orderFinalization:
      inputTopic: "payment-results-topic"

logging:
  level: "info"  # Options: debug, info, warn, error, fatal
  format: "json" # Options: json, text
  output: "stdout" # Options: stdout, stderr, or a file path

database:
  inMemory: true
  # connectionString: "user:password@/dbname" # Uncomment if using an actual DB


application:
  environment: "development" # Options: development, production
  # Other custom settings...
